//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custommers.CustommerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Custommer", Namespace="http://schemas.datacontract.org/2004/07/Manager.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Custommer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDCustommerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IDCustommer {
            get {
                return this.IDCustommerField;
            }
            set {
                if ((this.IDCustommerField.Equals(value) != true)) {
                    this.IDCustommerField = value;
                    this.RaisePropertyChanged("IDCustommer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resume {
            get {
                return this.ResumeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResumeField, value) != true)) {
                    this.ResumeField = value;
                    this.RaisePropertyChanged("Resume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Manager.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustommerService.ICustommerService")]
    public interface ICustommerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustommerService/GetCustommers", ReplyAction="http://tempuri.org/ICustommerService/GetCustommersResponse")]
        Custommers.CustommerService.Custommer[] GetCustommers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustommerService/GetCustommers", ReplyAction="http://tempuri.org/ICustommerService/GetCustommersResponse")]
        System.Threading.Tasks.Task<Custommers.CustommerService.Custommer[]> GetCustommersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustommerService/GetCustommerByID", ReplyAction="http://tempuri.org/ICustommerService/GetCustommerByIDResponse")]
        Custommers.CustommerService.Custommer GetCustommerByID(System.Guid ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustommerService/GetCustommerByID", ReplyAction="http://tempuri.org/ICustommerService/GetCustommerByIDResponse")]
        System.Threading.Tasks.Task<Custommers.CustommerService.Custommer> GetCustommerByIDAsync(System.Guid ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustommerService/AddCustommer", ReplyAction="http://tempuri.org/ICustommerService/AddCustommerResponse")]
        Custommers.CustommerService.Error[] AddCustommer(Custommers.CustommerService.Custommer custommer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustommerService/AddCustommer", ReplyAction="http://tempuri.org/ICustommerService/AddCustommerResponse")]
        System.Threading.Tasks.Task<Custommers.CustommerService.Error[]> AddCustommerAsync(Custommers.CustommerService.Custommer custommer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustommerServiceChannel : Custommers.CustommerService.ICustommerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustommerServiceClient : System.ServiceModel.ClientBase<Custommers.CustommerService.ICustommerService>, Custommers.CustommerService.ICustommerService {
        
        public CustommerServiceClient() {
        }
        
        public CustommerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustommerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustommerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustommerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Custommers.CustommerService.Custommer[] GetCustommers() {
            return base.Channel.GetCustommers();
        }
        
        public System.Threading.Tasks.Task<Custommers.CustommerService.Custommer[]> GetCustommersAsync() {
            return base.Channel.GetCustommersAsync();
        }
        
        public Custommers.CustommerService.Custommer GetCustommerByID(System.Guid ID) {
            return base.Channel.GetCustommerByID(ID);
        }
        
        public System.Threading.Tasks.Task<Custommers.CustommerService.Custommer> GetCustommerByIDAsync(System.Guid ID) {
            return base.Channel.GetCustommerByIDAsync(ID);
        }
        
        public Custommers.CustommerService.Error[] AddCustommer(Custommers.CustommerService.Custommer custommer) {
            return base.Channel.AddCustommer(custommer);
        }
        
        public System.Threading.Tasks.Task<Custommers.CustommerService.Error[]> AddCustommerAsync(Custommers.CustommerService.Custommer custommer) {
            return base.Channel.AddCustommerAsync(custommer);
        }
    }
}
